function [fitresult, gof] = createFit(EffectiveDE_Org, EffectiveFE_Org)
%CREATEFIT(EFFECTIVEDE_ORG,EFFECTIVEFE_ORG)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : EffectiveDE_Org
%      Y Output: EffectiveFE_Org
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Oct-2018 10:11:56


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( EffectiveDE_Org, EffectiveFE_Org );

% Set up fittype and options.
ft = fittype( 'power1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.144469612829218 -0.487051104906933];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'EffectiveFE_Org vs. EffectiveDE_Org', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel EffectiveDE_Org
ylabel EffectiveFE_Org
grid on


